export const JOURNAL_SUGGESTIONS: string[] = [
  'The New England Journal of Medicine',
  'JAMA',
  'JAMA Internal Medicine',
  'JAMA Network Open',
  'JAMA Pediatrics',
  'The Lancet',
  'The Lancet Oncology',
  'BMJ',
  'Nature',
  'Nature Medicine',
  'Science',
  'Cell',
  'Annals of Internal Medicine',
  'Circulation',
  'European Heart Journal',
  'Journal of the American College of Cardiology',
  'Stroke',
  'Diabetes Care',
  'Journal of Clinical Oncology',
  'Blood',
  'Gastroenterology',
  'Pediatrics',
  'Clinical Infectious Diseases',
  'American Journal of Public Health',
  'Health Affairs',
]
